trigger:
- main

pool:
  name: Default

steps:

- script: |
    python -m unittest test_app.py
  displayName: 'Run Application Tests'

- script: |
    docker build -t devops-demo:$(Build.BuildId) .
  displayName: 'Build Docker Image'